main: me.zombie_striker.psudocommands.PsudoCommands
version: ${project.version}
name: PsudoCommand
api-version: 1.16
authors:
  - Zombie_Striker (original author)
  - cricri_21 (lot of fixes)
  - Kamesuta (execute feature)
commands:
  psudo:
    description: Issues another command, as the console, supporting the base-minecraft @ function.
    permission: psudocommand.psudo
  psudouuid:
    description: Issues another command, as the player specified, supporting the base-minecraft @ function, except it returns the entities uuid.
    permission: psudocommand.psudouuid
  psudoas:
    description: Issues another command, as the player specified, supporting the base-minecraft @ function.
    permission: psudocommand.psudoas
  psudoasraw:
    description: Issues another command, as the player specified, ignoring base-minecraft @ function.
    permission: psudocommand.psudoasraw
permissions:
   psudocommand.*:
     description: Gives access to all Psudo commands
     children:
       psudocommand.psudo: true
       psudocommand.psudoas: true
       psudocommand.psudouuid: true